server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/interaction_db

  kafka:
    bootstrap-servers: localhost:9092

kafka:
  topic: interactions-topic

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
