server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/interaction_db

kafka:
  topic: media-interactions

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: interaction-group
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
