server:
  port: 8082

spring:
  application:
    name: mediaservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/media

management:
  endpoints:
    web:
      exposure:
        include: "*"
